"""
check_urls.py — weekly dead-link checker for studios.json

Reads studios.json, GETs every website URL, and reports
any that return 404 / 410 or fail to connect entirely.

Exit codes:
  0 — all URLs healthy (or no URLs to check)
  1 — one or more dead/unreachable URLs found

Writes to $GITHUB_OUTPUT when run inside GitHub Actions.
"""

import json
import os
import sys
import time
import requests
from datetime import datetime, timezone

REPO_ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STUDIOS_FILE = os.path.join(REPO_ROOT, "studios.json")
TIMEOUT      = 15   # seconds per request
DELAY        = 0.5  # seconds between requests (be polite)

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (compatible; StudioChecker/1.0; "
        "+https://github.com/roybotbot/ceramics-map)"
    )
}


def check_url(url: str) -> tuple[int | None, str | None]:
    """
    Returns (status_code, error_message).
    status_code is None when a network-level error occurs.
    """
    try:
        resp = requests.get(
            url,
            timeout=TIMEOUT,
            allow_redirects=True,
            headers=HEADERS,
        )
        return resp.status_code, None
    except requests.exceptions.Timeout:
        return None, "timeout"
    except requests.exceptions.SSLError:
        return None, "SSL error"
    except requests.exceptions.ConnectionError:
        return None, "connection error"
    except Exception as e:
        return None, str(e)


def is_dead(status: int | None, error: str | None) -> bool:
    """
    True when the URL is a strong signal that a studio has closed.
    - 404 Not Found / 410 Gone  → page is explicitly missing
    - None status (network err) → domain / server completely unreachable
    We skip 5xx (server hiccups) and other 4xx like 403 (access denied).
    """
    if status in (404, 410):
        return True
    if status is None:   # network-level failure
        return True
    return False


def build_report(dead: list[dict], checked: int) -> str:
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"## Studio URL Check — {date}",
        "",
        f"Checked **{checked}** studio URLs. "
        f"Found **{len(dead)}** that look dead or unreachable.",
        "",
    ]

    # Split into 404s vs connection failures for clarity
    hard_404 = [d for d in dead if d["status"] in (404, 410)]
    unreachable = [d for d in dead if d["status"] is None]

    if hard_404:
        lines += [
            "### 404 / 410 — page not found",
            "",
            "| Studio | Address | URL | Status |",
            "|--------|---------|-----|--------|",
        ]
        for d in hard_404:
            lines.append(
                f"| {d['name']} | {d['address']} | {d['url']} | HTTP {d['status']} |"
            )
        lines.append("")

    if unreachable:
        lines += [
            "### Unreachable — network / connection failure",
            "",
            "| Studio | Address | URL | Error |",
            "|--------|---------|-----|-------|",
        ]
        for d in unreachable:
            lines.append(
                f"| {d['name']} | {d['address']} | {d['url']} | {d['error']} |"
            )
        lines.append("")

    lines += [
        "---",
        "_Auto-generated by the weekly studio URL checker. "
        "Verify these studios are still operating and update `studios.json` accordingly. "
        "Close this issue once resolved._",
    ]
    return "\n".join(lines)


def write_github_output(dead_count: int, report: str) -> None:
    output_file = os.environ.get("GITHUB_OUTPUT")
    if not output_file:
        return
    with open(output_file, "a") as f:
        f.write(f"dead_count={dead_count}\n")
        f.write("report_body<<REPORT_EOF\n")
        f.write(report)
        f.write("\nREPORT_EOF\n")


def main() -> int:
    with open(STUDIOS_FILE) as f:
        data = json.load(f)

    features = data.get("features", [])
    urls_to_check = [
        (feat["properties"]["name"],
         feat["properties"].get("address", ""),
         feat["properties"]["website"].strip())
        for feat in features
        if feat["properties"].get("website", "").strip()
    ]

    print(f"Checking {len(urls_to_check)} studio URLs…", flush=True)

    dead = []
    for i, (name, address, url) in enumerate(urls_to_check, 1):
        status, error = check_url(url)
        flag = "✗" if is_dead(status, error) else "✓"
        label = f"HTTP {status}" if status else error
        print(f"  [{i:3}/{len(urls_to_check)}] {flag}  {label:20s}  {url}", flush=True)

        if is_dead(status, error):
            dead.append({"name": name, "address": address, "url": url,
                         "status": status, "error": error})

        time.sleep(DELAY)

    print(f"\nDead URLs: {len(dead)}")

    if dead:
        report = build_report(dead, len(urls_to_check))
        print("\n" + report)
        write_github_output(len(dead), report)
        return 1

    write_github_output(0, "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
